apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: todoapp
  POSTGRES_USER: user

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE TABLE
      IF NOT EXISTS todos
      (
        id SERIAL PRIMARY KEY,
        task TEXT NOT NULL
      );
  
