# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-volume
# spec: 
#   capacity:
#     storage: 5Gi
#   accessmodes:
#     - ReadWriteMany
#   local:
#     path: /storage/data


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi